sudo: required

language: go

go:
  - 1.9
  - tip

go_import_path: openpitrix.io/openpitrix

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

before_script:
  - docker --version
  - docker-compose version

script:
    - make fmt-check
    - make ci-test
