sudo: required

services:
  - docker

language: go

go:
  - 1.9
  - tip

go_import_path: openpitrix.io/openpitrix

env:
  - DOCKER_COMPOSE_VERSION=1.20.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker --version
  - docker-compose version

jobs:
  include:
    - stage: fmt-check
      script: make fmt-check
    - stage: ci-test
      script: make ci-test
