// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixUpdateClusterEnvRequest openpitrix update cluster env request
// swagger:model openpitrixUpdateClusterEnvRequest
type OpenpitrixUpdateClusterEnvRequest struct {

	// advanced param
	AdvancedParam []string `json:"advanced_param"`

	// cluster id
	ClusterID string `json:"cluster_id,omitempty"`

	// env
	Env string `json:"env,omitempty"`
}

// Validate validates this openpitrix update cluster env request
func (m *OpenpitrixUpdateClusterEnvRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixUpdateClusterEnvRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixUpdateClusterEnvRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixUpdateClusterEnvRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
