// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OpenpitrixApp openpitrix app
// swagger:model openpitrixApp
type OpenpitrixApp struct {

	// app id
	AppID string `json:"app_id,omitempty"`

	// category set
	CategorySet []*OpenpitrixResourceCategory `json:"category_set"`

	// chart name
	ChartName string `json:"chart_name,omitempty"`

	// create time
	// Format: date-time
	CreateTime strfmt.DateTime `json:"create_time,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// home
	Home string `json:"home,omitempty"`

	// icon
	Icon string `json:"icon,omitempty"`

	// keywords
	Keywords string `json:"keywords,omitempty"`

	// latest app version
	LatestAppVersion *OpenpitrixAppVersion `json:"latest_app_version,omitempty"`

	// maintainers
	Maintainers string `json:"maintainers,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// readme
	Readme string `json:"readme,omitempty"`

	// repo id
	RepoID string `json:"repo_id,omitempty"`

	// screenshots
	Screenshots string `json:"screenshots,omitempty"`

	// sources
	Sources string `json:"sources,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// status time
	// Format: date-time
	StatusTime strfmt.DateTime `json:"status_time,omitempty"`

	// update time
	// Format: date-time
	UpdateTime strfmt.DateTime `json:"update_time,omitempty"`
}

// Validate validates this openpitrix app
func (m *OpenpitrixApp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategorySet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatestAppVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixApp) validateCategorySet(formats strfmt.Registry) error {

	if swag.IsZero(m.CategorySet) { // not required
		return nil
	}

	for i := 0; i < len(m.CategorySet); i++ {
		if swag.IsZero(m.CategorySet[i]) { // not required
			continue
		}

		if m.CategorySet[i] != nil {
			if err := m.CategorySet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("category_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OpenpitrixApp) validateCreateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.CreateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("create_time", "body", "date-time", m.CreateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OpenpitrixApp) validateLatestAppVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.LatestAppVersion) { // not required
		return nil
	}

	if m.LatestAppVersion != nil {
		if err := m.LatestAppVersion.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latest_app_version")
			}
			return err
		}
	}

	return nil
}

func (m *OpenpitrixApp) validateStatusTime(formats strfmt.Registry) error {

	if swag.IsZero(m.StatusTime) { // not required
		return nil
	}

	if err := validate.FormatOf("status_time", "body", "date-time", m.StatusTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OpenpitrixApp) validateUpdateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("update_time", "body", "date-time", m.UpdateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixApp) UnmarshalBinary(b []byte) error {
	var res OpenpitrixApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
