// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixCeaseClustersRequest openpitrix cease clusters request
// swagger:model openpitrixCeaseClustersRequest
type OpenpitrixCeaseClustersRequest struct {

	// advanced param
	AdvancedParam []string `json:"advanced_param"`

	// cluster id
	ClusterID []string `json:"cluster_id"`
}

// Validate validates this openpitrix cease clusters request
func (m *OpenpitrixCeaseClustersRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixCeaseClustersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixCeaseClustersRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixCeaseClustersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
