// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeJobsResponse openpitrix describe jobs response
// swagger:model openpitrixDescribeJobsResponse
type OpenpitrixDescribeJobsResponse struct {

	// job set
	JobSet []*OpenpitrixJob `json:"job_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe jobs response
func (m *OpenpitrixDescribeJobsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeJobsResponse) validateJobSet(formats strfmt.Registry) error {

	if swag.IsZero(m.JobSet) { // not required
		return nil
	}

	for i := 0; i < len(m.JobSet); i++ {
		if swag.IsZero(m.JobSet[i]) { // not required
			continue
		}

		if m.JobSet[i] != nil {
			if err := m.JobSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("job_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeJobsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeJobsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeJobsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
