// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OpenpitrixGetAppVersionPackageFilesResponse openpitrix get app version package files response
// swagger:model openpitrixGetAppVersionPackageFilesResponse
type OpenpitrixGetAppVersionPackageFilesResponse struct {

	// files
	Files map[string]strfmt.Base64 `json:"files,omitempty"`

	// version id
	VersionID string `json:"version_id,omitempty"`
}

// Validate validates this openpitrix get app version package files response
func (m *OpenpitrixGetAppVersionPackageFilesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFiles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixGetAppVersionPackageFilesResponse) validateFiles(formats strfmt.Registry) error {

	if swag.IsZero(m.Files) { // not required
		return nil
	}

	for k := range m.Files {

		if swag.IsZero(m.Files[k]) { // not required
			continue
		}

		if err := validate.FormatOf("files"+"."+k, "body", "byte", m.Files[k].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixGetAppVersionPackageFilesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixGetAppVersionPackageFilesResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixGetAppVersionPackageFilesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
