// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteReposResponse openpitrix delete repos response
// swagger:model openpitrixDeleteReposResponse
type OpenpitrixDeleteReposResponse struct {

	// repo id
	RepoID []string `json:"repo_id"`
}

// Validate validates this openpitrix delete repos response
func (m *OpenpitrixDeleteReposResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteReposResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteReposResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteReposResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
