// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeClustersResponse openpitrix describe clusters response
// swagger:model openpitrixDescribeClustersResponse
type OpenpitrixDescribeClustersResponse struct {

	// cluster set
	ClusterSet []*OpenpitrixCluster `json:"cluster_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe clusters response
func (m *OpenpitrixDescribeClustersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeClustersResponse) validateClusterSet(formats strfmt.Registry) error {

	if swag.IsZero(m.ClusterSet) { // not required
		return nil
	}

	for i := 0; i < len(m.ClusterSet); i++ {
		if swag.IsZero(m.ClusterSet[i]) { // not required
			continue
		}

		if m.ClusterSet[i] != nil {
			if err := m.ClusterSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cluster_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeClustersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeClustersResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeClustersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
