// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixStartClustersRequest openpitrix start clusters request
// swagger:model openpitrixStartClustersRequest
type OpenpitrixStartClustersRequest struct {

	// advanced param
	AdvancedParam []string `json:"advanced_param"`

	// cluster id
	ClusterID []string `json:"cluster_id"`
}

// Validate validates this openpitrix start clusters request
func (m *OpenpitrixStartClustersRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixStartClustersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixStartClustersRequest) UnmarshalBinary(b []byte) error {
	var res OpenpitrixStartClustersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
