// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixStopClustersResponse openpitrix stop clusters response
// swagger:model openpitrixStopClustersResponse
type OpenpitrixStopClustersResponse struct {

	// cluster id
	ClusterID []string `json:"cluster_id"`

	// job id
	JobID []string `json:"job_id"`
}

// Validate validates this openpitrix stop clusters response
func (m *OpenpitrixStopClustersResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixStopClustersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixStopClustersResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixStopClustersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
