// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteRuntimesResponse openpitrix delete runtimes response
// swagger:model openpitrixDeleteRuntimesResponse
type OpenpitrixDeleteRuntimesResponse struct {

	// runtime id
	RuntimeID []string `json:"runtime_id"`
}

// Validate validates this openpitrix delete runtimes response
func (m *OpenpitrixDeleteRuntimesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteRuntimesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteRuntimesResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteRuntimesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
