// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeReposResponse openpitrix describe repos response
// swagger:model openpitrixDescribeReposResponse
type OpenpitrixDescribeReposResponse struct {

	// repo set
	RepoSet []*OpenpitrixRepo `json:"repo_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe repos response
func (m *OpenpitrixDescribeReposResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRepoSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeReposResponse) validateRepoSet(formats strfmt.Registry) error {

	if swag.IsZero(m.RepoSet) { // not required
		return nil
	}

	for i := 0; i < len(m.RepoSet); i++ {
		if swag.IsZero(m.RepoSet[i]) { // not required
			continue
		}

		if m.RepoSet[i] != nil {
			if err := m.RepoSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("repo_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeReposResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeReposResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeReposResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
