// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeSubnetsResponse openpitrix describe subnets response
// swagger:model openpitrixDescribeSubnetsResponse
type OpenpitrixDescribeSubnetsResponse struct {

	// subnet set
	SubnetSet []*OpenpitrixSubnet `json:"subnet_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe subnets response
func (m *OpenpitrixDescribeSubnetsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubnetSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeSubnetsResponse) validateSubnetSet(formats strfmt.Registry) error {

	if swag.IsZero(m.SubnetSet) { // not required
		return nil
	}

	for i := 0; i < len(m.SubnetSet); i++ {
		if swag.IsZero(m.SubnetSet[i]) { // not required
			continue
		}

		if m.SubnetSet[i] != nil {
			if err := m.SubnetSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("subnet_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeSubnetsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeSubnetsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeSubnetsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
