// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeCategoriesResponse openpitrix describe categories response
// swagger:model openpitrixDescribeCategoriesResponse
type OpenpitrixDescribeCategoriesResponse struct {

	// category set
	CategorySet []*OpenpitrixCategory `json:"category_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe categories response
func (m *OpenpitrixDescribeCategoriesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategorySet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeCategoriesResponse) validateCategorySet(formats strfmt.Registry) error {

	if swag.IsZero(m.CategorySet) { // not required
		return nil
	}

	for i := 0; i < len(m.CategorySet); i++ {
		if swag.IsZero(m.CategorySet[i]) { // not required
			continue
		}

		if m.CategorySet[i] != nil {
			if err := m.CategorySet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("category_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeCategoriesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeCategoriesResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeCategoriesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
