// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDescribeRepoEventsResponse openpitrix describe repo events response
// swagger:model openpitrixDescribeRepoEventsResponse
type OpenpitrixDescribeRepoEventsResponse struct {

	// repo event set
	RepoEventSet []*OpenpitrixRepoEvent `json:"repo_event_set"`

	// total count
	TotalCount int64 `json:"total_count,omitempty"`
}

// Validate validates this openpitrix describe repo events response
func (m *OpenpitrixDescribeRepoEventsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRepoEventSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDescribeRepoEventsResponse) validateRepoEventSet(formats strfmt.Registry) error {

	if swag.IsZero(m.RepoEventSet) { // not required
		return nil
	}

	for i := 0; i < len(m.RepoEventSet); i++ {
		if swag.IsZero(m.RepoEventSet[i]) { // not required
			continue
		}

		if m.RepoEventSet[i] != nil {
			if err := m.RepoEventSet[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("repo_event_set" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDescribeRepoEventsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDescribeRepoEventsResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDescribeRepoEventsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
